services:
  - type: web
    plan: free
    name: dev
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python devo
    repo: https://github.com/Teemsoha/dev.git
    branch: master
    autoDeploy: false
    envVars:
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
